# Sonar Rock vs Mine Prediction with Python

import the Dependencies

In [21]:
# %pip install numpy pandas scikit-learn

In [19]:
# import libraries

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

Data Collection and Data Processing

In [2]:
# loading dataset
sonar_data = pd.read_csv("sonar.csv", header= None)

In [3]:
# numbers of raws and columns
sonar_data.shape

(208, 61)

In [28]:
sonar_data.describe() #Describe --> Statistical measures of the data

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,...,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000
mean,0.029164,0.038437,0.043832,0.053892,0.075202,0.104570,0.121747,0.134799,0.178003,0.208259,...,0.016069,0.013420,0.010709,0.010941,0.009290,0.008222,0.007820,0.007949,0.007941,0.006507
std,0.022991,0.032960,0.038428,0.046528,0.055552,0.059105,0.061788,0.085152,0.118387,0.134416,...,0.012008,0.009634,0.007060,0.007301,0.007088,0.005736,0.005785,0.006470,0.006181,0.005031
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013350,0.016450,0.018950,0.024375,0.038050,0.067025,0.080900,0.080425,0.097025,0.111275,...,0.008425,0.007275,0.005075,0.005375,0.004150,0.004400,0.003700,0.003600,0.003675,0.003100
50%,0.022800,0.030800,0.034300,0.044050,0.062500,0.092150,0.106950,0.112100,0.152250,0.182400,...,0.013900,0.011400,0.009550,0.009300,0.007500,0.006850,0.005950,0.005800,0.006400,0.005300
75%,0.035550,0.047950,0.057950,0.064500,0.100275,0.134125,0.154000,0.169600,0.233425,0.268700,...,0.020825,0.016725,0.014900,0.014500,0.012100,0.010575,0.010425,0.010350,0.010325,0.008525
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900

In [27]:
sonar_data[60].unique()

array(['R', 'M'], dtype=object)

In [25]:
sonar_data[60].value_counts()

60
M    111
R     97
Name: count, dtype: int64

----
M --> Mine
-
R --> Rock
---

In [5]:
sonar_data.groupby(60).mean()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
60,,,,,,,,,,,,,,,,,,,,,
M,0.034989,0.045544,0.050720,0.064768,0.086715,0.111864,0.128359,0.149832,0.213492,0.251022,...,0.019352,0.016014,0.011643,0.012185,0.009923,0.008914,0.007825,0.009060,0.008695,0.006930
R,0.022498,0.030303,0.035951,0.041447,0.062028,0.096224,0.114180,0.117596,0.137392,0.159325,...,0.012311,0.010453,0.009640,0.009518,0.008567,0.007430,0.007814,0.006677,0.007078,0.006024

### Seperate data and lables

In [6]:
# Seperate data and lables

X = sonar_data.drop(columns= 60, axis= 1)
Y =sonar_data[60]

In [7]:
X

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0232,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0125,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0033,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0241,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0156,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,0.0187,0.0346,0.0168,0.0177,0.0393,0.1630,0.2028,0.1694,0.2328,0.2684,...,0.0203,0.0116,0.0098,0.0199,0.0033,0.0101,0.0065,0.0115,0.0193,0.0157
204,0.0323,0.0101,0.0298,0.0564,0.0760,0.0958,0.0990,0.1018,0.1030,0.2154,...,0.0051,0.0061,0.0093,0.0135,0.0063,0.0063,0.0034,0.0032,0.0062,0.0067
205,0.0522,0.0437,0.0180,0.0292,0.0351,0.1171,0.1257,0.1178,0.1258,0.2529,...,0.0155,0.0160,0.0029,0.0051,0.0062,0.0089,0.0140,0.0138,0.0077,0.0031
206,0.0303,0.0353,0.0490,0.0608,0.0167,0.1354,0.1465,0.1123,0.1945,0.2354,...,0.0042,0.0086,0.0046,0.0126,0.0036,0.0035,0.0034,0.0079,0.0036,0.0048
207,0.0260,0.0363,0.0136,0.0272,0.0214,0.0338,0.0655,0.1400,0.1843,0.2354,...,0.0181,0.0146,0.0129,0.0047,0.0039,0.0061,0.0040,0.0036,0.0061,0.0115

In [30]:
Y

0      R
1      R
2      R
3      R
4      R
      ..
203    M
204    M
205    M
206    M
207    M
Name: 60, Length: 208, dtype: object

### Tain Test Split

In [31]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size =0.1, stratify =Y, random_state =110 )

In [32]:
print("X_train:\n ",X_train,"\nshape: ", X_train.shape, "X_test", "\n", X_test,"\nshape: ", X_test.shape )

X_train:
           0       1       2       3       4       5       6       7       8   \
105  0.0116  0.0179  0.0449  0.1096  0.1913  0.0924  0.0761  0.1092  0.0757
117  0.0228  0.0106  0.0130  0.0842  0.1117  0.1506  0.1776  0.0997  0.1428
26   0.0151  0.0320  0.0599  0.1050  0.1163  0.1734  0.1679  0.1119  0.0889
60   0.0130  0.0006  0.0088  0.0456  0.0525  0.0778  0.0931  0.0941  0.1711
149  0.0207  0.0535  0.0334  0.0818  0.0740  0.0324  0.0918  0.1070  0.1553
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
68   0.0195  0.0142  0.0181  0.0406  0.0391  0.0249  0.0892  0.0973  0.0840
143  0.0516  0.0944  0.0622  0.0415  0.0995  0.2431  0.1777  0.2018  0.2611
29   0.0189  0.0308  0.0197  0.0622  0.0080  0.0789  0.1440  0.1451  0.1789
120  0.0346  0.0509  0.0079  0.0243  0.0432  0.0735  0.0938  0.1134  0.1228
9    0.0164  0.0173  0.0347  0.0070  0.0187  0.0671  0.1056  0.0697  0.0962

         9   ...      50      51      52      53      54      55      56  \
105  0.1006  ...  0.0031  0.0163  0.0099  0.0084  0.0270  0.0277  0.0097
117  0.2227  ...  0.0185  0.0098  0.0178  0.0077  0.0074  0.0095  0.0055
26   0.1205  ...  0.0086  0.0061  0.0015  0.0084  0.0128  0.0054  0.0011
60   0.1483  ...  0.0092  0.0078  0.0041  0.0013  0.0011  0.0045  0.0039
149  0.1234  ...  0.0171  0.0033  0.0050  0.0190  0.0103  0.0121  0.0042
..      ...  ...     ...     ...     ...     ...     ...     ...     ...
68   0.1191  ...  0.0125  0.0028  0.0067  0.0120  0.0012  0.0022  0.0058
143  0.1294  ...  0.0456  0.0432  0.0274  0.0152  0.0120  0.0129  0.0020
29   0.2522  ...  0.0091  0.0038  0.0096  0.0142  0.0190  0.0140  0.0099
120  0.1508  ...  0.0146  0.0040  0.0122  0.0107  0.0112  0.0102  0.0052
9    0.0251  ...  0.0118  0.0090  0.0223  0.0179  0.0084  0.0068  0.0032

         57      58      59
105  0.0054  0.0148  0.0092
117  0.0045  0.0063  0.0039
26   0.0019  0.0023  0.0062
60   0.0022  0.0023  0.0016
149  0.0090  0.0070  0.0099
..      ...     ...     ...
68   0.0042  0.0067  0.0012
143  0.0109  0.0074  0.0078
29   0.0092  0.0052  0.0075
120  0.0024  0.0079  0.0031
9    0.0035  0.0056  0.0040

[187 rows x 60 columns]
shape:  (187, 60) X_test
          0       1       2       3       4       5       6       7       8   \
84   0.0378  0.0318  0.0423  0.0350  0.1787  0.1635  0.0887  0.0817  0.1779
177  0.0201  0.0165  0.0344  0.0330  0.0397  0.0443  0.0684  0.0903  0.1739
144  0.0299  0.0688  0.0992  0.1021  0.0800  0.0629  0.0130  0.0813  0.1761
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598
112  0.0454  0.0472  0.0697  0.1021  0.1397  0.1493  0.1487  0.0771  0.1171
87   0.0856  0.0454  0.0382  0.0203  0.0385  0.0534  0.2140  0.3110  0.2837
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843
97   0.0491  0.0279  0.0592  0.1270  0.1772  0.1908  0.2217  0.0768  0.1246
196  0.0050  0.0017  0.0270  0.0450  0.0958  0.0830  0.0879  0.1220  0.1977
200  0.0131  0.0387  0.0329  0.0078  0.0721  0.1341  0.1626  0.1902  0.2610
47   0.0373  0.0281  0.0232  0.0225  0.0179  0.0733  0.0841  0.1031  0.0993
167  0.0137  0.0297  0.0116  0.0082  0.0241  0.0253  0.0279  0.0130  0.0489
195  0.0129  0.0141  0.0309  0.0375  0.0767  0.0787  0.0662  0.1108  0.1777
80   0.0229  0.0369  0.0040  0.0375  0.0455  0.1452  0.2211  0.1188  0.0750
186  0.0209  0.0191  0.0411  0.0321  0.0698  0.1579  0.1438  0.1402  0.3048
46   0.0308  0.0339  0.0202  0.0889  0.1570  0.1750  0.0920  0.1353  0.1593
81   0.0100  0.0194  0.0155  0.0489  0.0839  0.1009  0.1627  0.2071  0.2696
51   0.0131  0.0068  0.0308  0.0311  0.0085  0.0767  0.0771  0.0640  0.0726
5    0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105
158  0.0107  0.0453  0.0289  0.0713  0.1075  0.1019  0.1606  0.2119  0.3061
58   0.0225  0.0019  0.0075  0.0097  0.0445  0.0906  0.0889  0.0655  0.1624

         9   ...      50      51      52      53      54      55      56  \
84   0.2053  ...  0.0093  0.0046  0.0044  0.0078  0.0102  0.0065  0.0061
177  0.2571  ...  0.0125  0.0054  0.0057  0.0137  0.0109  0.0035  0.0056
144  0.0998  ...  0.0342  0.0459  0.0277  0.0172  0.0087  0.0046  0.0203
3    0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050
112  0.1675  ...  0.0137  0.0120  0.0042  0.0238  0.0129  0.0084  0.0218
87   0.2751  ...  0.0128  0.0172  0.0138  0.0079  0.0037  0.0051  0.0258
207  0.2354  ...  0.0181  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040
97   0.2028  ...  0.0268  0.0081  0.0129  0.0161  0.0063  0.0119  0.0194
196  0.2282  ...  0.0281  0.0165  0.0056  0.0010  0.0027  0.0062  0.0024
200  0.3193  ...  0.0137  0.0150  0.0076  0.0032  0.0037  0.0071  0.0040
47   0.0802  ...  0.0066  0.0008  0.0045  0.0024  0.0006  0.0073  0.0096
167  0.0874  ...  0.0169  0.0081  0.0040  0.0025  0.0036  0.0058  0.0067
195  0.2245  ...  0.0204  0.0124  0.0093  0.0072  0.0019  0.0027  0.0054
80   0.1631  ...  0.0115  0.0064  0.0022  0.0122  0.0151  0.0056  0.0026
186  0.3914  ...  0.0054  0.0078  0.0201  0.0104  0.0039  0.0031  0.0062
46   0.2795  ...  0.0070  0.0167  0.0127  0.0138  0.0090  0.0051  0.0029
81   0.2990  ...  0.0122  0.0130  0.0073  0.0077  0.0075  0.0060  0.0080
51   0.0901  ...  0.0109  0.0062  0.0028  0.0040  0.0075  0.0039  0.0053
5    0.3039  ...  0.0104  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057
158  0.2936  ...  0.0079  0.0164  0.0120  0.0113  0.0021  0.0097  0.0072
58   0.1452  ...  0.0051  0.0034  0.0129  0.0100  0.0044  0.0057  0.0030

         57      58      59
84   0.0062  0.0043  0.0053
177  0.0105  0.0082  0.0036
144  0.0130  0.0115  0.0015
3    0.0044  0.0040  0.0117
112  0.0321  0.0154  0.0053
87   0.0102  0.0037  0.0037
207  0.0036  0.0061  0.0115
97   0.0140  0.0332  0.0439
196  0.0063  0.0017  0.0028
200  0.0009  0.0015  0.0085
47   0.0054  0.0085  0.0060
167  0.0035  0.0043  0.0033
195  0.0017  0.0024  0.0029
80   0.0029  0.0104  0.0163
186  0.0087  0.0070  0.0042
46   0.0122  0.0056  0.0020
81   0.0019  0.0053  0.0019
51   0.0013  0.0052  0.0023
5    0.0027  0.0051  0.0062
158  0.0060  0.0017  0.0036
58   0.0035  0.0021  0.0027

[21 rows x 60 columns]
shape:  (21, 60)

In [37]:
print("\n Y_train: \n",Y_train,"\n shape: ", Y_train.shape, "\n Y_test\n", "\n", Y_test,"\n shape: ", Y_test.shape )

 Y_train:
 105    M
117    M
26     R
60     R
149    M
      ..
68     R
143    M
29     R
120    M
9      R
Name: 60, Length: 187, dtype: object
 shape:  (187,)
 Y_test

 84     R
177    M
144    M
3      R
112    M
87     R
207    M
97     M
196    M
200    M
47     R
167    M
195    M
80     R
186    M
46     R
81     R
51     R
5      R
158    M
58     R
Name: 60, dtype: object
 shape:  (21,)

### Model Training ==> Logistic Regression

In [12]:
model = LogisticRegression()

### Training the logistic regression model

In [39]:
model.fit(X_train, Y_train)

LogisticRegression()

### Evaulaion of Model

In [41]:
# Evaulation with accuracy
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score( y_pred= X_train_prediction, y_true= Y_train)

In [42]:
print("training_data_accuracy: ", training_data_accuracy)

training_data_accuracy:  0.8449197860962567

### Evaulation with accuracy

In [43]:
# Evaulation with accuracy
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(y_pred= X_test_prediction, y_true= Y_test )

In [44]:
print("test_data_accuracy: ", test_data_accuracy)

test_data_accuracy:  0.6190476190476191

### Making Prediction System

In [45]:
input_data= (0.0305,0.0363,0.0214,0.0227,0.0456,0.0665,0.0939,0.0972,0.2535,0.3127,0.2192,0.2621,0.2419,0.2179,0.1159,0.1237,0.0886,0.1755,0.1758,0.1540,0.0512,0.1805,0.4039,0.5697,0.6577,0.7474,0.8543,0.9085,0.8668,0.8892,0.9065,0.8522,0.7204,0.6200,0.6253,0.6848,0.7337,0.6281,0.5725,0.6119,0.5597,0.4965,0.5027,0.5772,0.5907,0.4803,0.3877,0.2779,0.1427,0.0424,0.0271,0.0200,0.0070,0.0070,0.0086,0.0089,0.0074,0.0042,0.0055,0.0021)
# Changing the input data to numpy array

input_data_as_array = np.asarray(input_data)

# Reshape np array as we are predicting for one instance

input_data_as_array_reshaped= input_data_as_array.reshape(1,-1)

prediction = model.predict(input_data_as_array_reshaped)

print(prediction)


if(prediction[0]== "R"):
  print("the object is Rock")
else:
  print("the object is Mine")

['M']
the object is Mine